# Generated by Django 5.0.6 on 2024-05-27 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default value', max_length=100)),
                ('description', models.CharField(default='default value', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='default value', max_length=100)),
                ('firstname', models.CharField(default='default value', max_length=100)),
                ('lastname', models.CharField(default='default value', max_length=100)),
                ('email', models.CharField(default='default value', max_length=100)),
                ('workphone', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('contact', models.CharField(default='default value', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='default value', max_length=100)),
                ('firstname', models.CharField(default='default value', max_length=100)),
                ('lastname', models.CharField(default='default value', max_length=100)),
                ('email', models.CharField(default='default value', max_length=100)),
                ('website', models.CharField(default='default value', max_length=100)),
                ('workphone', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('contact', models.CharField(default='default value', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default value', max_length=100)),
                ('address', models.CharField(default='default value', max_length=100)),
                ('city', models.CharField(default='default value', max_length=100)),
                ('country', models.CharField(default='default value', max_length=100)),
                ('area', models.CharField(default='default value', max_length=100)),
                ('capacity', models.IntegerField()),
                ('openingtime', models.IntegerField()),
                ('closingtime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default value', max_length=100)),
                ('date', models.DateField(default='default value', max_length=100)),
                ('date_due', models.DateField(default='default value', max_length=100)),
                ('payement_terms', models.CharField(default='default value', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='returnpack.client')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default value', max_length=100)),
                ('description', models.CharField(default='default value', max_length=100)),
                ('unit', models.CharField(default='default value', max_length=100)),
                ('dimensions', models.CharField(default='default value', max_length=100)),
                ('wieght', models.IntegerField()),
                ('brand', models.CharField(default='default value', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returnpack.category')),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='default value', max_length=100)),
                ('quantity', models.IntegerField(default='default value')),
                ('weight', models.FloatField(default='default value')),
                ('price', models.FloatField(default='default value')),
                ('capacity', models.FloatField(default='default value')),
                ('dimensions', models.FloatField(default='default value')),
                ('unit', models.CharField(default='default value', max_length=100)),
                ('durabilty', models.IntegerField(default='default value')),
                ('storagespace', models.FloatField(default='default value')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='returnpack.item')),
            ],
        ),
        migrations.CreateModel(
            name='Packagingmouvment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default value', max_length=100)),
                ('type', models.CharField(default='default value', max_length=100)),
                ('date', models.DateField(default='default value', max_length=100)),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='returnpack.packaging')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default='default value')),
                ('date', models.DateField(default='default value', max_length=100)),
                ('currency', models.CharField(default='default value', max_length=100)),
                ('paymeentmethod', models.IntegerField(default='default value')),
                ('quantity', models.IntegerField(default='default value')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='returnpack.item')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default='default value')),
                ('date', models.DateField(default='default value', max_length=100)),
                ('currency', models.CharField(default='default value', max_length=100)),
                ('paymeentmethod', models.IntegerField(default='default value')),
                ('quantity', models.IntegerField(default='default value')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='returnpack.item')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default='default value')),
                ('date', models.DateField(default='default value', max_length=100)),
                ('currency', models.CharField(default='default value', max_length=100)),
                ('paymeentmethod', models.IntegerField(default='default value')),
                ('quantity', models.IntegerField(default='default value')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='returnpack.item')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default value', max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='returnpack.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='returnpack.warehouse')),
            ],
        ),
    ]
