# Generated by Django 5.0.6 on 2024-05-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0004_remove_sales_paymeentmethod_sales_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paymeentmethod',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='paymeentmethod',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='currency',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
