# Generated by Django 5.0.6 on 2024-05-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0005_remove_payment_paymeentmethod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='item',
            new_name='item_id',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='default value', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='default value', max_length=100),
        ),
    ]
