# Generated by Django 5.0.6 on 2024-05-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0006_rename_item_payment_item_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact',
        ),
    ]
