# Generated by Django 5.0.6 on 2024-05-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0007_remove_client_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='item_id',
            new_name='item',
        ),
    ]
