# Generated by Django 5.0.6 on 2024-05-28 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0009_remove_bill_payement_terms_bill_payment_terms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='payment_terms',
        ),
        migrations.AddField(
            model_name='bill',
            name='payement_terms',
            field=models.CharField(default='default value', max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='returnpack.client'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default='default value', max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date_due',
            field=models.DateField(default='default value', max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.CharField(default='default value', max_length=100),
        ),
    ]
