# Generated by Django 5.0.6 on 2024-05-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0011_rename_payement_terms_bill_payment_terms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaging',
            name='durabilty',
        ),
    ]
