# Generated by Django 5.0.6 on 2024-05-29 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0013_remove_packagingmouvment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagingmouvment',
            old_name='type',
            new_name='mouvement',
        ),
    ]
