# Generated by Django 5.0.6 on 2024-05-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0014_rename_type_packagingmouvment_mouvement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Supplier',
        ),
    ]
