# Generated by Django 5.0.6 on 2024-05-29 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0015_rename_client_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='client',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(default='default value', on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='returnpack.item'),
        ),
    ]
