# Generated by Django 5.0.6 on 2024-05-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0016_rename_client_bill_customer_alter_purchase_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
