# Generated by Django 5.0.6 on 2024-05-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0017_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('company', 'Company'), ('customer', 'Customer')], default='default value', max_length=10),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='closingtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='openingtime',
            field=models.TimeField(),
        ),
    ]
