# Generated by Django 5.0.6 on 2024-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0018_warehouse_type_alter_warehouse_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packaging',
            name='capacity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='dimensions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='storagespace',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='type',
            field=models.CharField(default='returnable', max_length=100),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='unit',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
