# Generated by Django 5.0.6 on 2024-05-30 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0021_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default='default value', max_length=100)),
                ('status', models.CharField(default='default value', max_length=100)),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='returnpack.packaging')),
            ],
        ),
    ]
