# Generated by Django 5.0.6 on 2024-06-03 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0022_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='returnpack.customer'),
        ),
    ]
