# Generated by Django 5.0.6 on 2024-06-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0023_stock_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
